services:
  - type: web
    name: backend
    runtime: docker
    plan: starter
    dockerfilePath: ./platform/backend/Dockerfile
    dockerContext: ./platform/backend
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: CLIENT_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: hackonymous
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: pserv
    name: sqli-auth
    runtime: docker
    plan: starter
    dockerfilePath: ./vulnerable/sqli-auth/Dockerfile
    dockerContext: ./vulnerable/sqli-auth

  - type: pserv
    name: xss-search
    runtime: docker
    plan: starter
    dockerfilePath: ./vulnerable/xss-search/Dockerfile
    dockerContext: ./vulnerable/xss-search

  - type: web
    name: frontend
    runtime: docker
    plan: starter
    dockerfilePath: ./platform/frontend/Dockerfile
    dockerContext: ./platform/frontend
    healthCheckPath: /
    envVars:
      - key: VITE_API_BASE_URL
        value: /api
