CREATE DATABASE IF NOT EXISTS hackonymous;
USE hackonymous;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    phone VARCHAR(20),
    google_id VARCHAR(255) UNIQUE,
    avatar VARCHAR(255),
    provider ENUM('local', 'google') NOT NULL DEFAULT 'local',
    role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_admin TINYINT(1) NOT NULL DEFAULT 0,
    token_version INT NOT NULL DEFAULT 0,
    current_streak INT NOT NULL DEFAULT 0,
    max_streak INT NOT NULL DEFAULT 0,
    last_activity_date DATE NULL DEFAULT NULL,
    bio TEXT NULL DEFAULT NULL,
    location VARCHAR(255) NULL DEFAULT NULL,
    github VARCHAR(255) NULL DEFAULT NULL,
    twitter VARCHAR(255) NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS labs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    difficulty VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    points INTEGER NOT NULL,
    lab_url VARCHAR(255) NOT NULL,
    estimated_time INTEGER NOT NULL,
    flag VARCHAR(255) DEFAULT NULL,
    status ENUM('COMPLETED', 'PENDING') NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lab_meta (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lab_id INT NOT NULL UNIQUE,
    objectives JSON NOT NULL,
    scenario JSON NOT NULL,
    hints JSON NOT NULL,
    resources JSON NOT NULL,
    FOREIGN KEY (lab_id) REFERENCES labs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_lab_progress (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    lab_id INT NOT NULL,
    status ENUM('PENDING','COMPLETED') NOT NULL DEFAULT 'PENDING',
    points_earned INT NOT NULL DEFAULT 0,
    completed_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    current_streak INT NOT NULL DEFAULT 0,
    max_streak INT NOT NULL DEFAULT 0,
    last_activity_date DATE NULL DEFAULT NULL,
    hints_used INT NOT NULL DEFAULT 0,
    UNIQUE KEY uq_user_lab (user_id, lab_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (lab_id) REFERENCES labs(id) ON DELETE CASCADE
);
